install.packages("devtools")
library(devtools)
install_version("ggplot2", version = "3.4.2", repos = "http://cran.us.r-project.org")
install_version("statnet", version = "2019.6", repos = "http://cran.us.r-project.org")
install_version("dplyr", version = "1.1.2", repos = "http://cran.us.r-project.org")
install_version("RColorBrewer", version = "1.1-3", repos = "http://cran.us.r-project.org")
install_version("stringr", version = "1.5.0", repos = "http://cran.us.r-project.org")
install_version("ggseqlogo", version = "0.1", repos = "http://cran.us.r-project.org")
install_version("ggpubr", version = "0.6.0", repos = "http://cran.us.r-project.org")
install_version("reshape2", version = "1.4.4", repos = "http://cran.us.r-project.org")
install_version("GGally", version = "2.1.2", repos = "http://cran.us.r-project.org")
install_version("magrittr", version = "2.0.3", repos = "http://cran.us.r-project.org")
install.packages("ape")

if (!require("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install("proj4")
BiocManager::install("Biostrings")
BiocManager::install("msa")
BiocManager::install("ggtree")
BiocManager::install("ggmsa")
