if (!require("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install(c("proj4","msa","ggtree","ggmsa"))

install.packages("devtools")
library(devtools)
install_version("archive", version = "1.1.5", repos = "http://cran.us.r-project.org")
install_version("ape", version = "5.7-1", repos = "http://cran.us.r-project.org")
install_version("GGally", version = "2.1.2", repos = "http://cran.us.r-project.org")
install_version("ggseqlogo", version = "0.1", repos = "http://cran.us.r-project.org")
install_version("ggpubr", version = "0.6.0", repos = "http://cran.us.r-project.org")
install_version("ggridges", version = "0.5.4", repos = "http://cran.us.r-project.org")
install_version("ggraph", version = "2.1.0", repos = "http://cran.us.r-project.org")
install_version("magrittr", version = "2.0.3", repos = "http://cran.us.r-project.org")
install_version("pheatmap", version = "1.0.12", repos = "http://cran.us.r-project.org")
install_version("RColorBrewer", version = "1.1-3", repos = "http://cran.us.r-project.org")
install_version("reshape2", version = "1.4.4", repos = "http://cran.us.r-project.org")
install_version("rstatix", version = "0.7.2", repos = "http://cran.us.r-project.org")
install_version("stringdist", version = "0.9.10", repos = "http://cran.us.r-project.org")
install_version("stringr", version = "1.5.0", repos = "http://cran.us.r-project.org")
install_version("scales", version = "1.2.1", repos = "http://cran.us.r-project.org")
